#include "sprites.h"

static SDL_Rect spriteRects[SPR_COUNT];

void init_sprites()
{
    spriteRects[SPR_PLAYER] = (SDL_Rect){4 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_BULLET1] = (SDL_Rect){2 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_BULLET2] = (SDL_Rect){2 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER1] = (SDL_Rect){0 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER1_ALT] = (SDL_Rect){1 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER2] = (SDL_Rect){0 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER2_ALT] = (SDL_Rect){1 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER3] = (SDL_Rect){0 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_INVADER3_ALT] = (SDL_Rect){1 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_UFO] = (SDL_Rect){3 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_EXPLOSION1] = (SDL_Rect){2 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_EXPLOSION2] = (SDL_Rect){1 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_SHIELD_LEFT] = (SDL_Rect){3 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_SHIELD_MID] = (SDL_Rect){3 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
    spriteRects[SPR_SHIELD_RIGHT] = (SDL_Rect){3 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE};
}

SDL_Rect get_sprite(SpriteID id)
{
    return spriteRects[id];
}
