name: Build PixelInvaders

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # -------------------------------
    # Dependencies (Linux)
    # -------------------------------
    - name: Cache APT packages
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential pkg-config \
          libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev zip

    # -------------------------------
    # Dependencies (macOS)
    # -------------------------------
    - name: Cache Homebrew
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar
        key: ${{ runner.os }}-brew-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-brew-

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer zip

    # -------------------------------
    # Dependencies (Windows)
    # -------------------------------
    - name: Cache SDL2 Windows Dependencies
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v4
      with:
        path: build/SDL2*
        key: ${{ runner.os }}-sdl2-${{ hashFiles('cmake/SetupSDL2.cmake') }}
        restore-keys: |
          ${{ runner.os }}-sdl2-

    - name: Install Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install 7zip -y

    # -------------------------------
    # Configure & Build
    # -------------------------------
    - name: Configure and Build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release

    # -------------------------------
    # Copy DLLs (Windows)
    # -------------------------------
    - name: Copy SDL2 DLLs
      if: matrix.os == 'windows-latest'
      run: |
        xcopy build\SDL2\lib\x64\*.dll build\Release\
        xcopy build\SDL2_image\lib\x64\*.dll build\Release\
        xcopy build\SDL2_ttf\lib\x64\*.dll build\Release\
        xcopy build\SDL2_mixer\lib\x64\*.dll build\Release\

    # -------------------------------
    # Install Game (Clean Dist Folder)
    # -------------------------------
    - name: Install Game
      run: |
        cmake --install build --config Release --prefix dist

    # -------------------------------
    # macOS Binary Stripping
    # -------------------------------
    - name: Strip macOS Binary
      if: matrix.os == 'macos-latest'
      run: |
        strip -u -r dist/PixelInvaders

    # -------------------------------
    # Package Game
    # -------------------------------
    - name: Package Game
      run: |
        cd dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a ../PixelInvaders-${{ matrix.os }}.zip *
        else
          zip -r ../PixelInvaders-${{ matrix.os }}.zip .
        fi
        cd ..

    # -------------------------------
    # Upload Artifact
    # -------------------------------
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: PixelInvaders-${{ matrix.os }}
        path: PixelInvaders-${{ matrix.os }}.zip
